config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users

  root to: 'pages#home'

  resources :events, only: [:index, :show, :create, :new] do
    post 'invite_users', on: :member
    resources :lists, only: [:create]
  end

  resources :lists, only: [:index, :new, :show] do
    resources :ideas, only: [:new, :create]
  end




  get '/giftlist', to: 'ideas#index'

  resources :ideas, only: [:edit, :update, :show, :destroy] do

    member do
      patch "bought"
    end
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user

  after_create :broadcast_message


  def broadcast_message
    ActionCable.server.broadcast("list_#{idea.list.id}", {
      comment_partial: ApplicationController.renderer.render(
        partial: "lists/comment_li",
        locals: { comment: self, user_is_messages_author: false }
      ),
      idea_id: idea.id
    })
  end
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :emails
  belongs_to :user
  has_secure_token
  has_many :lists, dependent: :destroy
  accepts_nested_attributes_for :lists
  validates :name, presence: true
  validates :date, presence: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :list
  belongs_to :chosen_by, optional: true, class_name: "User", foreign_key: "chosen_by_id"
  has_many :comments, dependent: :destroy
  has_one_attached :photo
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :ideas, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :lists, dependent: :destroy

  has_many :ideas, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create!(description: params[:comment][:description], idea: Idea.find(params[:idea_id]), user: current_user)
    ActionCable.server.broadcast("idea#{@comment.idea}", {
      comment: @comment.to_json
    })
    respond_to do |format|
      format.html do
        redirect_to list_path(Idea.find(params[:idea_id]).list)
      end
      format.js
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @user = current_user
    @events = Event.all
    @ideas = Idea.all

    @event = Event.new
    @event.lists.build
  end

  def show
    @user = current_user
    @event = Event.find_by(id: params[:id])
    @event = Event.find_by(token: params[:id]) if @event.nil?

    @lists = @event.lists
    @ideas = Idea.all
  end

  def new
    @event = Event.new
    @event.lists.build
  end

  def create
    @event = Event.new(events_params)
    @event.user = current_user
    @event.lists.last.user = current_user
    @event.save
    redirect_to list_path(@event.lists.first.id)
  end

  def invite_users
    @event = Event.find(params[:id])
    @emails = params[:emails].reject(&:empty?)

    @emails.each do |email|
      UserMailer.with(email: email, inviter: current_user, event: @event).welcome.deliver_now
    end

    redirect_to events_path
  end

  def events_params
    params.require(:event).permit(:name, :date, lists_attributes: [:title])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all.order(id: :asc)
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new
    @list = current_user.lists.find(params[:list_id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def create
    @list = current_user.lists.find(params[:list_id])
    @idea = Idea.new(ideas_params)
    @idea.user = current_user
    @idea.list = @list

    if @idea.save
      redirect_to list_path(@idea.list)
    else
      render :new
    end
  end

  def update

    @idea = Idea.find(params[:id])
    @is_me = @idea.list.user == current_user
    @list = params[:list]
    @bought = params[:bought]

    if @idea.update(ideas_params)
        ActionCable.server.broadcast("list_#{@idea.list.id}", {
          idea_content_partial: ApplicationController.renderer.render(
            partial: "lists/list_show_ideacontent",
            locals: { list: @idea.list, idea: @idea, current_user: current_user }
          ),
          idea_id: @idea.id
        })

      respond_to do |format|
        format.html { redirect_to event_path(@idea.list.event) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'events/show' }
        format.js  # <-- idem
      end
    end
  end

  def bought
    @idea = Idea.find(params[:id])
    @idea.update(bought: !@idea.bought)
    respond_to do |format|
      format.html do
        redirect_to '/giftlist'
      end
      format.js #
    end


  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to '/events'
  end

  def ideas_params
    params.require(:idea).permit(:title, :description, :url, :photo, :chosen_by_id, :status, :bought)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @user = current_user
  end

  def show
    @list = List.find(params[:id])

    # response en fonction du type de réponse souhaitée
    # Cas html
    # Cas js
  end


  def lists_params
    params.require(:list).permit(:title, :description)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @event = Event.new
    @event.lists.build
    # @event.user = current_user

    # if !@event.user
    #   redirect_to new_user_registration
    # else
    #   redirect_to events_path
    # end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
  end
end

# if !current_user.braintree_customer_id?
#   session[:stored_product_id] = @product.id
#   redirect_to "/customer/new"
# else
#   redirect_to view_item_path(@product.id)
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def idea_chosen_by_user
    @list = current_user.lists.find(params[:list_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper

  def meta_type
    content_for?(:meta_type) ? content_for(:meta_type) : DEFAULT_META["meta_type"]
  end

  def meta_url
    content_for?(:meta_url) ? content_for(:meta_url) : DEFAULT_META["meta_url"]
  end

  def meta_product_name
    content_for?(:meta_product_name) ? content_for(:meta_product_name) : DEFAULT_META["meta_product_name"]
  end

  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/comments/create.js.erb
// function refreshPage() {
//   // const ideaComment = document.getElementById("idea_<%= @comment.idea.id %>");
//   // ideaComment.insertAdjacentHTML("beforeend", "<%= j render 'lists/comment_li', comment: @comment %>");
// }



function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById("form_idea_<%= @comment.idea.id%>");
  newCommentForm.innerHTML = innerHTML;
}
// refreshPage();
refreshForm("<%= j render 'lists/comment_form', idea: @comment.idea %>");

app/views/comments/new_comment.html.erb
<h1>Comments#new_comment</h1>
<p>Find me in app/views/comments/new_comment.html.erb</p>

app/views/events/_event_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header-white">
        <button type="button" class="close p-4" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p class="modal-title nouvelle-idee" id="exampleModalLongTitle">NOUVEL EVENEMENT</p>
      </div>
      <div class="modal-body">
        <div class="topo">
          <p> Je crée ma nouvelle fiesta ici !</p>
        </div>

        <%= simple_form_for event do |f| %>
        <div class="form-group">

          <%= f.input :name, placeholder: 'Mon évènement', label: false, input_html: { class: 'form-spe' } %>
        </div>
        <div class="form-group">
          <%= f.simple_fields_for :lists do |l| %>
            <%= l.input :title, placeholder: 'Ma liste', label: false, input_html: { class: 'form-spe' }  %>

          <% end %>
        </div>
          <%= f.input :date, as: :string, required: false, label: false, placeholder: "Date des festivités", input_html: {class: "datepicker"} %>
          <%= f.submit "Créer", class: "btn btn-primary btn-bleu" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/events/_idea_modal.erb
<li class="d-flex idea-card align-items-center justify-content-between">
  <div class="d-flex">

    <div class=" align-items-center justify-content-center mr-3">
      <%= cl_image_tag idea.photo.key, height: 150, width: 150 if idea.photo %>
    </div>
    <div class="idea-title">
      <h5> <strong> <%= idea.title %> </strong><h5/>
        <p><%= idea.description %></p>
    </div>
  </div>

  <% unless is_me %>

    <% if idea.chosen_by_id.nil? || idea.chosen_by == current_user %>
      <%= simple_form_for(idea, remote: true) do |f| %>
        <%= f.input :chosen_by_id, as: :hidden, input_html: { value: idea.chosen_by_id.nil? ? current_user.id : nil } %>
        <%= f.input :status, as: :hidden, input_html: { value: !idea.status } %>
        <button type="submit" class="<%= idea.chosen_by_id == current_user.id ? 'btn btn-selected m-2' : 'btn btn-primary m-2' %>">
          <%= idea.chosen_by_id == current_user.id ? 'Rendre' : 'Choisir' %>
        </button>
      <% end %>
    <% else %>

      <div class="d-flex align-items-center profile-img">
        <%#= link_to 'idea_path(idea)' do %>
          <%= cl_image_tag idea.chosen_by.photo.key, class: "avatar-small"%>
        <%# end %>
      </div>
    <% end %>

  <% end %>
</li>

app/views/events/_list_modal.html.erb
<!-- Modal -->
<div class="modal fade" id='<%= "staticBackdrop#{list.id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title nouvelle-idee" id="exampleModalLongTitle">NOUVELLE IDEE</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="topo">
          <p>Je rentre vite ma nouvelle idée ici!</p>
        </div>

        <%= simple_form_for [list,  Idea.new] do |f| %>
          <div class="form-group">
            <%= f.input :title, placeholder: 'Titre', label: false, input_html: { class: 'form-spe' } %>
          </div>
          <div class="form-group">
            <%= f.input :description, placeholder: 'Description', label: false, input_html: { class: 'form-spe' } %>
          </div>
          <div class="form-group">
            <%= f.input :url, placeholder: 'URL', label: false, input_html: { class: 'form-spe' } %>
          </div>
          <label class="pointer" for='<%= "idea_photo#{list.id}" %>'>📷 Ajouter une photo</label>
          <%= f.input :photo, as: :file, label: false, input_html: { class: "d-none", id: "idea_photo#{list.id}" } %>
          <%= f.submit "Ajouter", class: "btn btn-primary btn-bleu" %>
        <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-fluid pt-4">
  <div class="row">
    <% @events.each do |event| %>
      <div class = event_container >
        <div class = "titre_event">
          <h2 id="events-title" class="view"><%= link_to event.name.upcase, event_path(event) %></h2>
          <% event.lists.where(user: current_user).each do |list| %>
            <div class="list-idea-card">
              <div class="idea-card-title text-center d-flex align-items-center justify-content-center">
                <h4 class='mb-0 hoover-list'><%= link_to "#{list.title}", list_path(list) %></h4>
              </div>

              <div class="idea-card-body pt-2">
                <div class="idea-wrappers pr-2">
                  <% list.ideas.each do |idea| %>
                    <div class="idea-wrapper">
                      <div class="idea-wrapper-icon">
                        <% if idea.photo.attached? %>
                          <%= cl_image_tag idea.photo.key, width: 75, height: 75, crop: :fit %>
                        <% end %>
                      </div>
                      <div class="idea-wrapper-text ml-1">
                        <strong><%= idea.title.upcase %></strong>
                        <div class="idea-wrapper-description">
                          <%= idea.description.upcase %>
                        </div>
                      </div>
                      <div class="d-flex align-items-center">
                        <%= link_to edit_idea_path(idea) do %>
                          <%= image_tag 'picto_modifier.png', width: 40 %>
                        <% end %>
                        <%= link_to idea_path(idea), method: :delete do %>
                          <%= image_tag 'picto_corbeille.png', width: 20 %>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
  <!-- NEW EVENT -->

<!--   Button trigger modal -->
<!--<button type="button" class="btn btn-primary btn-bleu" data-toggle="modal" data-target="#staticBackdrop">-->
<!--  Créer un évènement-->
<!--</button>-->

<!-- Modal -->

  <div class="centered">
<div class="pop-up-new-product">
  <h5 class="nouvelle-idee">NOUVEL EVENEMENT</h5>

  <div class="form-container mt-5 mb-4">
  <p>Je crée ma nouvelle fiesta ici !</p>

  <%= simple_form_for @event do |f| %>
    <%= f.input :name, placeholder: 'Nom de mon évènement :', label: false, input_html: { class: 'form-spe' } %>
    <%= f.simple_fields_for :lists do |l| %>
      <%= l.input :title, placeholder: 'Nom de ma liste :', label: false, input_html: { class: 'form-spe' }  %>
    <% end %>
    <%= f.input :date, placeholder: 'Date :', label: false, input_html: { class: 'form-spe' } %>
    <%= f.submit "Créer", class: "btn btn-primary btn-bleu" %>
  <% end %>
  </div>
</div>
  </div>

app/views/events/show.html.erb
<div class="wrapper-yield">

  <div class="circle-div">
    <div class="title-event" >
      <h1><%= @event.name %></h1>
      <a class="button-coral btn-clipboard text-white" data-clipboard-text='<%= event_url(@event.token) %>'
        data-toggle="tooltip" data-title='Copié' >
        Inviter un proche
      </a>
    </div>

    <ul class='circle-container'>
      <% @lists.each do |list| %>
        <% is_me = list.user == @user %>
        <li>
          <div class='grow'>
            <%= cl_image_tag list.user.photo.key, class: "avatar-bordered #{'avatar-bordered-me' if is_me}", data: { toggle: "modal", target: "#modal-list-#{list.id}" } %>
            <span class="user-name"><%= list.user.name %></span>
          </div>
        </li>
      <% end %>
    </ul>

    <% @lists.each do |list| %>
      <% is_me = list.user == @user %>
      <div class="modal fade" id="modal-list-<%= list.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header <%= 'modal-header-me' if is_me %>">
              <div class="d-flex align-items-center">
                <%= cl_image_tag list.user.photo.key, class: "avatar-small mr-3", data: { toggle: "modal", target: "#modal-list-#{list.id}" } %>
                <h3 class="hoover-list"><%= link_to "#{list.title}", list_path(list) %></h3>
              </div>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>


            <div class="modal-body">

              <% list.ideas.each do |idea| %>

                <div id="modal-idea-<%=idea.id%>">
                <%= render 'idea_modal', idea: idea, is_me: is_me %>
                </div>

              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>


  </div>
</div>

app/views/ideas/_idea_modal.html.erb
<div class="idea-container <%= idea.bought ? 'bought' : '' %> pl-2">
  <div class="d-flex idea-card align-content-center justify-content-between m-2 p-2">

    <div class="d-flex">

      <div class="d-flex align-items-center justify-content-center mr-3">
        <%= cl_image_tag idea.photo.key, height: 175, width: 175 if idea.photo %>
      </div>

      <div class="gift-title ml-1 pt-2">
        <strong><%= idea.title.upcase %></strong>
        <div class="gift-description">
          <%= idea.description %>
        </div>
      </div>

    </div>


    <div class="forms-container d-flex align-items-center justify-content-center flex-column">


      <% if idea.bought %>
        <div class="emoji mr-4">
        <%= link_to '✅', bought_idea_path(idea), method: :patch %>
        </div>
      <% else %>

        <div class="emoji mr-4">
        <%= link_to '⬜️', bought_idea_path(idea), method: :patch %>
        </div>

      <% end %>

      <%#= simple_form_for(idea, remote: true) do |f| %>
        <%#= f.input :chosen_by_id, as: :hidden, input_html: { value:  nil } %>
        <%#= f.input :status, as: :hidden, input_html: { value: false } %>
        <%#= f.input :bought, as: :hidden, input_html: { value: false } %>
<!--        <input class='d-none' type="text" name="giftlist" value=true>-->
<!--        <button type="submit" class="btn btn-selected m-2 acheter">Rendre</button>-->
      <%# end %>
    </div>

    <%#= simple_form_for(idea, remote:true) do |f| %>
      <%#= f.input :bought, as: :boolean%>
    <%# end %>

  </div>
</div>

app/views/ideas/bought.js.erb
function refreshPage() {
  const ideaContainer = document.getElementById('modal-idea-<%= @idea.id %>');
  ideaContainer.innerHTML = "<%= j render 'ideas/idea_modal', idea: @idea %>";
}

refreshPage();

app/views/ideas/edit.erb
<!-- NEW IDEA -->

<!-- Modal -->
<div class="centered">
<div class="pop-up-new-product">
  <h5 class="nouvelle-idee">NOUVELLE IDEE</h5>
  <div class="topo">
    <p>Je rentre vite ma nouvelle idée ici !</p>
  </div>

  <%= simple_form_for [@idea] do |f| %>
    <div class="form-group">
      <%= f.input :title, placeholder: 'Titre :', label: false, input_html: { class: 'form-spe' } %>
    </div>
    <div class="form-group">
      <%= f.input :description, placeholder: 'Description :', label: false, input_html: { class: 'form-spe' } %>
    </div>
    <div class="form-group">
      <%= f.input :url, placeholder: 'URL :', label: false, input_html: { class: 'form-spe' } %>
    </div>
    <label class="btn btn-primary btn-abricot" for="idea_photo">Photo</label>
    <%= f.input :photo, as: :file, label: false, input_html: { class: "d-none" } %>
    <%= f.submit "Ajouter mon idée", class: "btn btn-primary btn-bleu" %>
  <% end %>
</div>
</div>

app/views/ideas/index.html.erb
<div class="centered">
  <div class="gift-container">
    <div class="title mt-2 text-center">
      <h1> 🎁 Ma liste de courses 🎁</h1>

    </div>

    <div class="list-card2">

      <div class="idea-card-body d-flex justify-content-center align-items-center">
        <div class="idea-wrappers">

          <% @ideas.where(chosen_by_id: current_user.id).each do |idea| %>

            <div id="modal-idea-<%= idea.id %>">
              <%= render 'idea_modal', idea: idea %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
  <!-- NEW IDEA -->

  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-bleu" data-toggle="modal" data-target="#staticBackdrop">
  Enrichir ma liste
</button>

<!-- Modal -->
<div class="pop-up-new-product">
        <h5 class="nouvelle-idee">NOUVELLE IDEE</h5>
        <div class="topo">
          <p>Je rentre vite ma nouvelle idée ici !</p>
        </div>

        <%= simple_form_for [@list, @idea] do |f| %>
        <div class="form-group">
          <%= f.input :title, placeholder: 'Titre :', label: false, input_html: { class: 'form-spe' } %>
        </div>
        <div class="form-group">
          <%= f.input :description, placeholder: 'Description :', label: false, input_html: { class: 'form-spe' } %>
        </div>
        <div class="form-group">
          <%= f.input :url, placeholder: 'URL :', label: false, input_html: { class: 'form-spe' } %>
        </div>
          <label class="btn btn-primary btn-abricot" for="idea_photo">Ajouter une photo</label>
          <%= f.input :photo, as: :file, label: false, input_html: { class: "d-none" } %>
          <%= f.submit "Ajouter mon idée", class: "btn btn-primary btn-bleu" %>
        <% end %>
</div>

app/views/ideas/show.html.erb
<div class="alignement d-flex justify-content-center align-items-center">
  <div class="idea-container-show mt-5">
      <div class="idea-card">
        <div class="d-flex align-items-center justify-content-center">
          <%= cl_image_tag @idea.photo.key, crop: :fill if @idea.photo %>
        </div>
        <div class="box">
          <div class="idea-text">
            <h4><%= @idea.title %></h4>
            <p><%= @idea.description %></p>
          </div>
          <a href="/"><div class="btn btn-primary p-2">Home</div></a>
        </div>
      </div>
  </div>
</div>

app/views/ideas/update.js.erb
// app/views/reviews/create.js.erb
// Here you generate *JavaScript* that would be executed in the browser
function replaceIdea(innerHTML) {
    const newIdeaList = document.getElementById('modal-idea-<%=@idea.id%>');
    newIdeaList.innerHTML = innerHTML;
}

function replaceListIdea(innerHTML) {
    const newIdeaList = document.getElementById('idea-<%=@idea.id%>');
    newIdeaList.innerHTML = innerHTML;
}

function removeIdea() {
    const newIdeaList = document.getElementById('modal-idea-<%=@idea.id%>');
    while (newIdeaList.firstChild) {
        newIdeaList.removeChild(newIdeaList.firstChild);
    }
}

<% if @list %>
replaceListIdea('<%= j render "lists/idea_modal", idea: @idea, is_me:@is_me %>')
<% else %>
  replaceIdea('<%= j render "events/idea_modal", idea: @idea, is_me:@is_me %>')
<% end %>

app/views/lists/_comment_form.html.erb
<%= simple_form_for([idea, Comment.new], remote: true) do |f| %>
  <%= f.input :description, as: :string, placeholder: 'Mon commentaire ...' %>
  <div class="d-none" >
  <%= f.submit %>
  </div>
<% end %>

app/views/lists/_comment_li.html.erb
<li>
  <%= cl_image_tag comment.user.photo.key, class: "avatar-comment mr-3" %>
  <%= comment.description %>
</li>

app/views/lists/_idea_modal.html.erb
<% unless is_me %>
  <% if idea.chosen_by_id.nil? || idea.chosen_by == current_user %>
    <%= simple_form_for(idea, remote: true) do |f| %>
      <%= f.input :chosen_by_id, as: :hidden, input_html: { value: idea.chosen_by_id.nil? ? current_user.id : nil } %>
      <%= f.input :status, as: :hidden, input_html: { value: !idea.status } %>
      <input class='d-none' type="text" name="list" value=true>
      <button type="submit" class="<%= idea.status ? 'btn btn-selected m-2' : 'btn btn-primary m-2' %>">
        <%= idea.status ? 'Rendre' : 'Choisir' %>
      </button>
    <% end %>
  <% else %>
    <div class="d-flex align-items-center profile-img">
      <%= link_to idea_path(idea) do %>
        <%= cl_image_tag idea.chosen_by.photo.key, class: "avatar-small"%>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/lists/show.html.erb
<div class="list_container">
  <div class="basile">
    <h2 id="events-title" class="view"><%= link_to @list.event.name.upcase, event_path(@list.event) %></h2>
    <%= cl_image_tag @list.user.photo.key, class: "avatar-small mr-3" %>
  </div>
    <ul class="list-card">
      <% @list.ideas.each do |idea| %>
        <div id="idea_container_<%= idea.id%>">
          <%= render 'lists/list_show_ideacontent', list: @list, idea: idea, current_user: current_user %>
        </div>



      <% end %>

      <% if @list.user == current_user %>
      <!-- modal add idea -->
      <div class="grow-card btn-center" type="" data-toggle="modal" data-target='#<%= "staticBackdrop#{@list.id}" %>' style="display: flex; align-items: center; justify-content: center;">
        <%= image_tag 'picto_add.png', width: 60, class: "picto-add" %>
      </div>

<div class= "mt-3">
   <%= simple_form_for @list.event, url: invite_users_event_path(@list.event), method: :post  do |f| %>
    <%= f.input :emails, collection: [], input_html: { class: "js-example-basic-multiple", name: "emails[]", multiple: "multiple"}, label: "Invite ta MIF à l'événement !" %>
    <%= f.submit "Envoyer", class: "btn btn-primary btn-bleu" %>
   <% end %>

</div>
      <% end %>

    </ul>

</div>

<!-- modal idea -->
  <%= render 'lists/modal_white', list: @list %>


  <% content_for :after_js do %>
    <script>

      scrollLastMessageIntoView();
      App['list_<%= @list.id %>'] = App.cable.subscriptions.create({ channel: 'ListsChannel', list_id: <%= @list.id %>}, {
        received: (data) => {
          if (data.comment_partial) {
            const ideaComment = document.getElementById(`idea_${data.idea_id}`);
            ideaComment.insertAdjacentHTML("beforeend", data.comment_partial);
            scrollLastMessageIntoView();
          }

          if (data.idea_content_partial) {
            const ideaContent = document.getElementById(`idea_container_${data.idea_id}`);
            ideaContent.innerHTML = data.idea_content_partial;
          }
        }
      })
    </script>
  <% end %>